title: Walker Lab
description: >-
  Enzyme selectivity for engineering biosynthesis.
  Department of Chemistry and Chemical Biology, University of New Mexico.
url: "https://mcw-lab.github.io"
baseurl: ""

author: Mark C. Walker

markdown: kramdown
permalink: /:title/
